"""Initial migration

Revision ID: 19422db95ef8
Revises: 5b7bf561026e
Create Date: 2025-06-13 11:26:31.420159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19422db95ef8'
down_revision = '5b7bf561026e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('default_risk_percent', sa.Float(), nullable=True),
    sa.Column('account_size', sa.Float(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('email_verification_token', sa.String(length=100), nullable=True),
    sa.Column('token_generated_at', sa.DateTime(), nullable=True),
    sa.Column('password_reset_token', sa.String(length=100), nullable=True),
    sa.Column('password_reset_token_generated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('email_verification_token'),
    sa.UniqueConstraint('password_reset_token'),
    sa.UniqueConstraint('username')
    )
    op.create_table('trade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('trade_type', sa.String(length=20), nullable=False),
    sa.Column('entry_date', sa.DateTime(), nullable=False),
    sa.Column('exit_date', sa.DateTime(), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('entry_reason', sa.Text(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('exit_reason', sa.Text(), nullable=True),
    sa.Column('strike_price', sa.Float(), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('option_type', sa.String(length=10), nullable=True),
    sa.Column('premium_paid', sa.Float(), nullable=True),
    sa.Column('implied_volatility', sa.Float(), nullable=True),
    sa.Column('is_spread', sa.Boolean(), nullable=True),
    sa.Column('spread_type', sa.String(length=30), nullable=True),
    sa.Column('long_strike', sa.Float(), nullable=True),
    sa.Column('short_strike', sa.Float(), nullable=True),
    sa.Column('long_premium', sa.Float(), nullable=True),
    sa.Column('short_premium', sa.Float(), nullable=True),
    sa.Column('net_credit', sa.Float(), nullable=True),
    sa.Column('max_profit', sa.Float(), nullable=True),
    sa.Column('max_loss', sa.Float(), nullable=True),
    sa.Column('breakeven_price', sa.Float(), nullable=True),
    sa.Column('delta', sa.Float(), nullable=True),
    sa.Column('gamma', sa.Float(), nullable=True),
    sa.Column('theta', sa.Float(), nullable=True),
    sa.Column('vega', sa.Float(), nullable=True),
    sa.Column('underlying_price_at_entry', sa.Float(), nullable=True),
    sa.Column('underlying_price_at_exit', sa.Float(), nullable=True),
    sa.Column('profit_loss', sa.Float(), nullable=True),
    sa.Column('profit_loss_percent', sa.Float(), nullable=True),
    sa.Column('market_condition', sa.String(length=50), nullable=True),
    sa.Column('setup_type', sa.String(length=100), nullable=True),
    sa.Column('timeframe', sa.String(length=20), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('take_profit', sa.Float(), nullable=True),
    sa.Column('risk_amount', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tags', sa.String(length=200), nullable=True),
    sa.Column('entry_chart_image', sa.String(length=200), nullable=True),
    sa.Column('exit_chart_image', sa.String(length=200), nullable=True),
    sa.Column('is_analyzed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trading_journal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('journal_date', sa.Date(), nullable=False),
    sa.Column('daily_pnl', sa.Float(), nullable=True),
    sa.Column('market_outlook', sa.Text(), nullable=True),
    sa.Column('daily_goals', sa.Text(), nullable=True),
    sa.Column('what_went_well', sa.Text(), nullable=True),
    sa.Column('what_went_wrong', sa.Text(), nullable=True),
    sa.Column('lessons_learned', sa.Text(), nullable=True),
    sa.Column('tomorrow_focus', sa.Text(), nullable=True),
    sa.Column('emotional_state', sa.String(length=50), nullable=True),
    sa.Column('stress_level', sa.Integer(), nullable=True),
    sa.Column('discipline_score', sa.Integer(), nullable=True),
    sa.Column('ai_daily_feedback', sa.Text(), nullable=True),
    sa.Column('daily_score', sa.Integer(), nullable=True),
    sa.Column('market_trend', sa.String(length=50), nullable=True),
    sa.Column('volatility', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'journal_date', name='uix_user_journal_date')
    )
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('auto_analyze_trades', sa.Boolean(), nullable=True),
    sa.Column('auto_create_journal', sa.Boolean(), nullable=True),
    sa.Column('analysis_detail_level', sa.String(length=20), nullable=True),
    sa.Column('daily_journal_reminder', sa.Boolean(), nullable=True),
    sa.Column('weekly_summary', sa.Boolean(), nullable=True),
    sa.Column('default_chart_timeframe', sa.String(length=10), nullable=True),
    sa.Column('trades_per_page', sa.Integer(), nullable=True),
    sa.Column('default_risk_percent', sa.Float(), nullable=True),
    sa.Column('max_daily_loss', sa.Float(), nullable=True),
    sa.Column('max_position_size', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('trade_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=True),
    sa.Column('strengths', sa.Text(), nullable=True),
    sa.Column('weaknesses', sa.Text(), nullable=True),
    sa.Column('improvement_areas', sa.Text(), nullable=True),
    sa.Column('actionable_drills', sa.Text(), nullable=True),
    sa.Column('entry_analysis', sa.Text(), nullable=True),
    sa.Column('exit_analysis', sa.Text(), nullable=True),
    sa.Column('risk_analysis', sa.Text(), nullable=True),
    sa.Column('market_context', sa.Text(), nullable=True),
    sa.Column('options_analysis', sa.Text(), nullable=True),
    sa.Column('chart_analysis', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('key_lessons', sa.Text(), nullable=True),
    sa.Column('future_setups', sa.Text(), nullable=True),
    sa.Column('analysis_date', sa.DateTime(), nullable=True),
    sa.Column('ai_model_used', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['trade_id'], ['trade.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trade_analysis')
    op.drop_table('user_settings')
    op.drop_table('trading_journal')
    op.drop_table('trade')
    op.drop_table('user')
    # ### end Alembic commands ###
