"""Add missing journal fields

Revision ID: 6a8be1fc25aa
Revises: a15b33f58c52
Create Date: 2025-06-23 00:47:09.690811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a8be1fc25aa'
down_revision = 'a15b33f58c52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trading_journal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('market_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('trading_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('emotions', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('tomorrow_plan', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trading_journal', schema=None) as batch_op:
        batch_op.drop_column('tomorrow_plan')
        batch_op.drop_column('emotions')
        batch_op.drop_column('trading_notes')
        batch_op.drop_column('market_notes')

    # ### end Alembic commands ###
