"""add chart fields to trades

Revision ID: 1791717e920b
Revises: d1add_user_reset_columns
Create Date: 2025-10-26 14:04:36.479321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1791717e920b'
down_revision = 'd1add_user_reset_columns'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('chart_annotations', sa.Text(), nullable=True))
    op.add_column('trades', sa.Column('chart_snapshot_path', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trades', 'chart_snapshot_path')
    op.drop_column('trades', 'chart_annotations')
    # ### end Alembic commands ###
