"""Add confirmation fields to MarketBriefSubscriber

Revision ID: becbf99ab3eb
Revises: a5981c5b3284
Create Date: 2025-07-30 00:00:31.200713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'becbf99ab3eb'
down_revision = 'a5981c5b3284'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('market_brief_subscriber', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('token', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('confirmed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_brief_sent', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.create_unique_constraint(None, ['token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('market_brief_subscriber', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('is_active')
        batch_op.drop_column('last_brief_sent')
        batch_op.drop_column('confirmed_at')
        batch_op.drop_column('token')
        batch_op.drop_column('confirmed')

    # ### end Alembic commands ###
